worlds:
  world:
    biomes:
      OCEAN: OCEAN
      PLAINS: PLAINS
      DESERT: DESERT
      EXTREME_HILLS: EXTREME_HILLS
      FOREST: FOREST
      TAIGA: TAIGA
      SWAMPLAND: SWAMPLAND
      RIVER: RIVER
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: ICE_FLATS
      ICE_MOUNTAINS: ICE_MOUNTAINS
      MUSHROOM_ISLAND: MUSHROOM_ISLAND
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: BEACHES
      DESERT_HILLS: DESERT_HILLS
      FOREST_HILLS: FOREST_HILLS
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: JUNGLE
      JUNGLE_HILLS: JUNGLE_HILLS
      JUNGLE_EDGE: JUNGLE_EDGE
      DEEP_OCEAN: DEEP_OCEAN
      STONE_BEACH: STONE_BEACH
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: BIRCH_FOREST
      BIRCH_FOREST_HILLS: BIRCH_FOREST_HILLS
      ROOFED_FOREST: ROOFED_FOREST
      TAIGA_COLD: TAIGA_COLD
      TAIGA_COLD_HILLS: TAIGA_COLD_HILLS
      REDWOOD_TAIGA: REDWOOD_TAIGA
      REDWOOD_TAIGA_HILLS: REDWOOD_TAIGA_HILLS
      EXTREME_HILLS_WITH_TREES: EXTREME_HILLS_WITH_TREES
      SAVANNA: SAVANNA
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: MESA
      MESA_ROCK: MESA_ROCK
      MESA_CLEAR_ROCK: MESA_CLEAR_ROCK
      VOID: VOID
      MUTATED_PLAINS: MUTATED_PLAINS
      MUTATED_DESERT: MUTATED_DESERT
      MUTATED_EXTREME_HILLS: MUTATED_EXTREME_HILLS
      MUTATED_FOREST: MUTATED_FOREST
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: MUTATED_SWAMPLAND
      MUTATED_ICE_FLATS: MUTATED_ICE_FLATS
      MUTATED_JUNGLE: MUTATED_JUNGLE
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: MUTATED_BIRCH_FOREST
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: MUTATED_ROOFED_FOREST
      MUTATED_TAIGA_COLD: MUTATED_TAIGA_COLD
      MUTATED_REDWOOD_TAIGA: MUTATED_REDWOOD_TAIGA
      MUTATED_REDWOOD_TAIGA_HILLS: MUTATED_REDWOOD_TAIGA_HILLS
      MUTATED_EXTREME_HILLS_WITH_TREES: MUTATED_EXTREME_HILLS_WITH_TREES
      MUTATED_SAVANNA: MUTATED_SAVANNA
      MUTATED_SAVANNA_ROCK: MUTATED_SAVANNA_ROCK
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
  world_nether:
    biomes:
      OCEAN: OCEAN
      PLAINS: PLAINS
      DESERT: DESERT
      EXTREME_HILLS: EXTREME_HILLS
      FOREST: FOREST
      TAIGA: TAIGA
      SWAMPLAND: SWAMPLAND
      RIVER: RIVER
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: ICE_FLATS
      ICE_MOUNTAINS: ICE_MOUNTAINS
      MUSHROOM_ISLAND: MUSHROOM_ISLAND
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: BEACHES
      DESERT_HILLS: DESERT_HILLS
      FOREST_HILLS: FOREST_HILLS
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: JUNGLE
      JUNGLE_HILLS: JUNGLE_HILLS
      JUNGLE_EDGE: JUNGLE_EDGE
      DEEP_OCEAN: DEEP_OCEAN
      STONE_BEACH: STONE_BEACH
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: BIRCH_FOREST
      BIRCH_FOREST_HILLS: BIRCH_FOREST_HILLS
      ROOFED_FOREST: ROOFED_FOREST
      TAIGA_COLD: TAIGA_COLD
      TAIGA_COLD_HILLS: TAIGA_COLD_HILLS
      REDWOOD_TAIGA: REDWOOD_TAIGA
      REDWOOD_TAIGA_HILLS: REDWOOD_TAIGA_HILLS
      EXTREME_HILLS_WITH_TREES: EXTREME_HILLS_WITH_TREES
      SAVANNA: SAVANNA
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: MESA
      MESA_ROCK: MESA_ROCK
      MESA_CLEAR_ROCK: MESA_CLEAR_ROCK
      VOID: VOID
      MUTATED_PLAINS: MUTATED_PLAINS
      MUTATED_DESERT: MUTATED_DESERT
      MUTATED_EXTREME_HILLS: MUTATED_EXTREME_HILLS
      MUTATED_FOREST: MUTATED_FOREST
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: MUTATED_SWAMPLAND
      MUTATED_ICE_FLATS: MUTATED_ICE_FLATS
      MUTATED_JUNGLE: MUTATED_JUNGLE
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: MUTATED_BIRCH_FOREST
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: MUTATED_ROOFED_FOREST
      MUTATED_TAIGA_COLD: MUTATED_TAIGA_COLD
      MUTATED_REDWOOD_TAIGA: MUTATED_REDWOOD_TAIGA
      MUTATED_REDWOOD_TAIGA_HILLS: MUTATED_REDWOOD_TAIGA_HILLS
      MUTATED_EXTREME_HILLS_WITH_TREES: MUTATED_EXTREME_HILLS_WITH_TREES
      MUTATED_SAVANNA: MUTATED_SAVANNA
      MUTATED_SAVANNA_ROCK: MUTATED_SAVANNA_ROCK
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
  world_the_end:
    biomes:
      OCEAN: OCEAN
      PLAINS: PLAINS
      DESERT: DESERT
      EXTREME_HILLS: EXTREME_HILLS
      FOREST: FOREST
      TAIGA: TAIGA
      SWAMPLAND: SWAMPLAND
      RIVER: RIVER
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: ICE_FLATS
      ICE_MOUNTAINS: ICE_MOUNTAINS
      MUSHROOM_ISLAND: MUSHROOM_ISLAND
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: BEACHES
      DESERT_HILLS: DESERT_HILLS
      FOREST_HILLS: FOREST_HILLS
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: JUNGLE
      JUNGLE_HILLS: JUNGLE_HILLS
      JUNGLE_EDGE: JUNGLE_EDGE
      DEEP_OCEAN: DEEP_OCEAN
      STONE_BEACH: STONE_BEACH
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: BIRCH_FOREST
      BIRCH_FOREST_HILLS: BIRCH_FOREST_HILLS
      ROOFED_FOREST: ROOFED_FOREST
      TAIGA_COLD: TAIGA_COLD
      TAIGA_COLD_HILLS: TAIGA_COLD_HILLS
      REDWOOD_TAIGA: REDWOOD_TAIGA
      REDWOOD_TAIGA_HILLS: REDWOOD_TAIGA_HILLS
      EXTREME_HILLS_WITH_TREES: EXTREME_HILLS_WITH_TREES
      SAVANNA: SAVANNA
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: MESA
      MESA_ROCK: MESA_ROCK
      MESA_CLEAR_ROCK: MESA_CLEAR_ROCK
      VOID: VOID
      MUTATED_PLAINS: MUTATED_PLAINS
      MUTATED_DESERT: MUTATED_DESERT
      MUTATED_EXTREME_HILLS: MUTATED_EXTREME_HILLS
      MUTATED_FOREST: MUTATED_FOREST
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: MUTATED_SWAMPLAND
      MUTATED_ICE_FLATS: MUTATED_ICE_FLATS
      MUTATED_JUNGLE: MUTATED_JUNGLE
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: MUTATED_BIRCH_FOREST
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: MUTATED_ROOFED_FOREST
      MUTATED_TAIGA_COLD: MUTATED_TAIGA_COLD
      MUTATED_REDWOOD_TAIGA: MUTATED_REDWOOD_TAIGA
      MUTATED_REDWOOD_TAIGA_HILLS: MUTATED_REDWOOD_TAIGA_HILLS
      MUTATED_EXTREME_HILLS_WITH_TREES: MUTATED_EXTREME_HILLS_WITH_TREES
      MUTATED_SAVANNA: MUTATED_SAVANNA
      MUTATED_SAVANNA_ROCK: MUTATED_SAVANNA_ROCK
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
  oakley_snow:
    biomes:
      OCEAN: Muns Resevoir
      PLAINS: PLAINS
      DESERT: DESERT
      EXTREME_HILLS: EXTREME_HILLS
      FOREST: FOREST
      TAIGA: TAIGA
      SWAMPLAND: SWAMPLAND
      RIVER: RIVER
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: ICE_FLATS
      ICE_MOUNTAINS: ICE_MOUNTAINS
      MUSHROOM_ISLAND: MUSHROOM_ISLAND
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: BEACHES
      DESERT_HILLS: DESERT_HILLS
      FOREST_HILLS: FOREST_HILLS
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: JUNGLE
      JUNGLE_HILLS: JUNGLE_HILLS
      JUNGLE_EDGE: JUNGLE_EDGE
      DEEP_OCEAN: Wir Sea
      STONE_BEACH: STONE_BEACH
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: BIRCH_FOREST
      BIRCH_FOREST_HILLS: BIRCH_FOREST_HILLS
      ROOFED_FOREST: ROOFED_FOREST
      TAIGA_COLD: TAIGA_COLD
      TAIGA_COLD_HILLS: TAIGA_COLD_HILLS
      REDWOOD_TAIGA: REDWOOD_TAIGA
      REDWOOD_TAIGA_HILLS: REDWOOD_TAIGA_HILLS
      EXTREME_HILLS_WITH_TREES: EXTREME_HILLS_WITH_TREES
      SAVANNA: SAVANNA
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: MESA
      MESA_ROCK: MESA_ROCK
      MESA_CLEAR_ROCK: MESA_CLEAR_ROCK
      VOID: VOID
      MUTATED_PLAINS: MUTATED_PLAINS
      MUTATED_DESERT: MUTATED_DESERT
      MUTATED_EXTREME_HILLS: MUTATED_EXTREME_HILLS
      MUTATED_FOREST: MUTATED_FOREST
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: MUTATED_SWAMPLAND
      MUTATED_ICE_FLATS: MUTATED_ICE_FLATS
      MUTATED_JUNGLE: MUTATED_JUNGLE
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: MUTATED_BIRCH_FOREST
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: MUTATED_ROOFED_FOREST
      MUTATED_TAIGA_COLD: MUTATED_TAIGA_COLD
      MUTATED_REDWOOD_TAIGA: MUTATED_REDWOOD_TAIGA
      MUTATED_REDWOOD_TAIGA_HILLS: MUTATED_REDWOOD_TAIGA_HILLS
      MUTATED_EXTREME_HILLS_WITH_TREES: MUTATED_EXTREME_HILLS_WITH_TREES
      MUTATED_SAVANNA: MUTATED_SAVANNA
      MUTATED_SAVANNA_ROCK: MUTATED_SAVANNA_ROCK
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
  build_world:
    biomes:
      OCEAN: OCEAN
      PLAINS: PLAINS
      DESERT: DESERT
      EXTREME_HILLS: EXTREME_HILLS
      FOREST: FOREST
      TAIGA: TAIGA
      SWAMPLAND: SWAMPLAND
      RIVER: RIVER
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: ICE_FLATS
      ICE_MOUNTAINS: ICE_MOUNTAINS
      MUSHROOM_ISLAND: MUSHROOM_ISLAND
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: BEACHES
      DESERT_HILLS: DESERT_HILLS
      FOREST_HILLS: FOREST_HILLS
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: JUNGLE
      JUNGLE_HILLS: JUNGLE_HILLS
      JUNGLE_EDGE: JUNGLE_EDGE
      DEEP_OCEAN: DEEP_OCEAN
      STONE_BEACH: STONE_BEACH
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: BIRCH_FOREST
      BIRCH_FOREST_HILLS: BIRCH_FOREST_HILLS
      ROOFED_FOREST: ROOFED_FOREST
      TAIGA_COLD: TAIGA_COLD
      TAIGA_COLD_HILLS: TAIGA_COLD_HILLS
      REDWOOD_TAIGA: REDWOOD_TAIGA
      REDWOOD_TAIGA_HILLS: REDWOOD_TAIGA_HILLS
      EXTREME_HILLS_WITH_TREES: EXTREME_HILLS_WITH_TREES
      SAVANNA: SAVANNA
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: MESA
      MESA_ROCK: MESA_ROCK
      MESA_CLEAR_ROCK: MESA_CLEAR_ROCK
      VOID: VOID
      MUTATED_PLAINS: MUTATED_PLAINS
      MUTATED_DESERT: MUTATED_DESERT
      MUTATED_EXTREME_HILLS: MUTATED_EXTREME_HILLS
      MUTATED_FOREST: MUTATED_FOREST
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: MUTATED_SWAMPLAND
      MUTATED_ICE_FLATS: MUTATED_ICE_FLATS
      MUTATED_JUNGLE: MUTATED_JUNGLE
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: MUTATED_BIRCH_FOREST
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: MUTATED_ROOFED_FOREST
      MUTATED_TAIGA_COLD: MUTATED_TAIGA_COLD
      MUTATED_REDWOOD_TAIGA: MUTATED_REDWOOD_TAIGA
      MUTATED_REDWOOD_TAIGA_HILLS: MUTATED_REDWOOD_TAIGA_HILLS
      MUTATED_EXTREME_HILLS_WITH_TREES: MUTATED_EXTREME_HILLS_WITH_TREES
      MUTATED_SAVANNA: MUTATED_SAVANNA
      MUTATED_SAVANNA_ROCK: MUTATED_SAVANNA_ROCK
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
  ivaindesert:
    biomes:
      OCEAN: The Burning Sands
      PLAINS: PLAINS
      DESERT: NEEDS NAME
      EXTREME_HILLS: EXTREME_HILLS
      FOREST: FOREST
      TAIGA: TAIGA
      SWAMPLAND: SWAMPLAND
      RIVER: Bloodrun
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: ICE_FLATS
      ICE_MOUNTAINS: ICE_MOUNTAINS
      MUSHROOM_ISLAND: MUSHROOM_ISLAND
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: BEACHES
      DESERT_HILLS: DESERT_HILLS
      FOREST_HILLS: FOREST_HILLS
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: JUNGLE
      JUNGLE_HILLS: JUNGLE_HILLS
      JUNGLE_EDGE: JUNGLE_EDGE
      DEEP_OCEAN: DEEP_OCEAN
      STONE_BEACH: STONE_BEACH
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: BIRCH_FOREST
      BIRCH_FOREST_HILLS: BIRCH_FOREST_HILLS
      ROOFED_FOREST: ROOFED_FOREST
      TAIGA_COLD: TAIGA_COLD
      TAIGA_COLD_HILLS: TAIGA_COLD_HILLS
      REDWOOD_TAIGA: REDWOOD_TAIGA
      REDWOOD_TAIGA_HILLS: REDWOOD_TAIGA_HILLS
      EXTREME_HILLS_WITH_TREES: EXTREME_HILLS_WITH_TREES
      SAVANNA: SAVANNA
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: Red Peaks
      MESA_ROCK: Red Flats
      MESA_CLEAR_ROCK: Sunguard
      VOID: VOID
      MUTATED_PLAINS: MUTATED_PLAINS
      MUTATED_DESERT: MUTATED_DESERT
      MUTATED_EXTREME_HILLS: MUTATED_EXTREME_HILLS
      MUTATED_FOREST: MUTATED_FOREST
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: MUTATED_SWAMPLAND
      MUTATED_ICE_FLATS: MUTATED_ICE_FLATS
      MUTATED_JUNGLE: MUTATED_JUNGLE
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: MUTATED_BIRCH_FOREST
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: MUTATED_ROOFED_FOREST
      MUTATED_TAIGA_COLD: MUTATED_TAIGA_COLD
      MUTATED_REDWOOD_TAIGA: MUTATED_REDWOOD_TAIGA
      MUTATED_REDWOOD_TAIGA_HILLS: MUTATED_REDWOOD_TAIGA_HILLS
      MUTATED_EXTREME_HILLS_WITH_TREES: MUTATED_EXTREME_HILLS_WITH_TREES
      MUTATED_SAVANNA: MUTATED_SAVANNA
      MUTATED_SAVANNA_ROCK: MUTATED_SAVANNA_ROCK
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
  Civex III Final:
    biomes:
      OCEAN: Blue Sea
      PLAINS: Riverlands
      DESERT: Javega
      EXTREME_HILLS: Roundtop
      FOREST: Risebank
      TAIGA: Claws of Azal
      SWAMPLAND: Gelie Delta
      RIVER: Riverways
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: Rime
      ICE_MOUNTAINS: High Helm
      MUSHROOM_ISLAND: Izan Waters
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: Southern Sea
      DESERT_HILLS: Golden Bay
      FOREST_HILLS: The Rim
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: Elderwoods
      JUNGLE_HILLS: Melara
      JUNGLE_EDGE: JUNGLE_EDGE
      DEEP_OCEAN: The Deep
      STONE_BEACH: Shineth's Tears
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: Gelie Forest
      BIRCH_FOREST_HILLS: Scattered Isles
      ROOFED_FOREST: Farlands
      TAIGA_COLD: The Scar
      TAIGA_COLD_HILLS: Eshen Bay
      REDWOOD_TAIGA: Moorwake
      REDWOOD_TAIGA_HILLS: Middling Wood
      EXTREME_HILLS_WITH_TREES: Whitestone Mountains
      SAVANNA: Westmarch
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: Far Deim
      MESA_ROCK: MESA_ROCK
      MESA_CLEAR_ROCK: Ascension
      VOID: VOID
      MUTATED_PLAINS: The Divide
      MUTATED_DESERT: Oltore
      MUTATED_EXTREME_HILLS: West Haikes
      MUTATED_FOREST: Ayatola
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: Uphaike
      MUTATED_ICE_FLATS: The Devil's Knives
      MUTATED_JUNGLE: Goldleaf
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: Low Valley
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: Ola
      MUTATED_TAIGA_COLD: Glass Waste
      MUTATED_REDWOOD_TAIGA: Eire
      MUTATED_REDWOOD_TAIGA_HILLS: Zemmet
      MUTATED_EXTREME_HILLS_WITH_TREES: East Haikes
      MUTATED_SAVANNA: Umn
      MUTATED_SAVANNA_ROCK: Greenridge
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
  rivervalleyjungle:
    biomes:
      OCEAN: OCEAN
      PLAINS: PLAINS
      DESERT: DESERT
      EXTREME_HILLS: EXTREME_HILLS
      FOREST: FOREST
      TAIGA: TAIGA
      SWAMPLAND: SWAMPLAND
      RIVER: RIVER
      HELL: HELL
      SKY: SKY
      FROZEN_OCEAN: FROZEN_OCEAN
      FROZEN_RIVER: FROZEN_RIVER
      ICE_FLATS: ICE_FLATS
      ICE_MOUNTAINS: ICE_MOUNTAINS
      MUSHROOM_ISLAND: MUSHROOM_ISLAND
      MUSHROOM_ISLAND_SHORE: MUSHROOM_ISLAND_SHORE
      BEACHES: BEACHES
      DESERT_HILLS: DESERT_HILLS
      FOREST_HILLS: FOREST_HILLS
      TAIGA_HILLS: TAIGA_HILLS
      SMALLER_EXTREME_HILLS: SMALLER_EXTREME_HILLS
      JUNGLE: JUNGLE
      JUNGLE_HILLS: JUNGLE_HILLS
      JUNGLE_EDGE: Tella
      DEEP_OCEAN: DEEP_OCEAN
      STONE_BEACH: STONE_BEACH
      COLD_BEACH: COLD_BEACH
      BIRCH_FOREST: BIRCH_FOREST
      BIRCH_FOREST_HILLS: BIRCH_FOREST_HILLS
      ROOFED_FOREST: ROOFED_FOREST
      TAIGA_COLD: TAIGA_COLD
      TAIGA_COLD_HILLS: TAIGA_COLD_HILLS
      REDWOOD_TAIGA: REDWOOD_TAIGA
      REDWOOD_TAIGA_HILLS: REDWOOD_TAIGA_HILLS
      EXTREME_HILLS_WITH_TREES: EXTREME_HILLS_WITH_TREES
      SAVANNA: SAVANNA
      SAVANNA_ROCK: SAVANNA_ROCK
      MESA: MESA
      MESA_ROCK: MESA_ROCK
      MESA_CLEAR_ROCK: MESA_CLEAR_ROCK
      VOID: VOID
      MUTATED_PLAINS: MUTATED_PLAINS
      MUTATED_DESERT: MUTATED_DESERT
      MUTATED_EXTREME_HILLS: MUTATED_EXTREME_HILLS
      MUTATED_FOREST: MUTATED_FOREST
      MUTATED_TAIGA: MUTATED_TAIGA
      MUTATED_SWAMPLAND: MUTATED_SWAMPLAND
      MUTATED_ICE_FLATS: MUTATED_ICE_FLATS
      MUTATED_JUNGLE: MUTATED_JUNGLE
      MUTATED_JUNGLE_EDGE: MUTATED_JUNGLE_EDGE
      MUTATED_BIRCH_FOREST: MUTATED_BIRCH_FOREST
      MUTATED_BIRCH_FOREST_HILLS: MUTATED_BIRCH_FOREST_HILLS
      MUTATED_ROOFED_FOREST: MUTATED_ROOFED_FOREST
      MUTATED_TAIGA_COLD: MUTATED_TAIGA_COLD
      MUTATED_REDWOOD_TAIGA: MUTATED_REDWOOD_TAIGA
      MUTATED_REDWOOD_TAIGA_HILLS: MUTATED_REDWOOD_TAIGA_HILLS
      MUTATED_EXTREME_HILLS_WITH_TREES: MUTATED_EXTREME_HILLS_WITH_TREES
      MUTATED_SAVANNA: MUTATED_SAVANNA
      MUTATED_SAVANNA_ROCK: MUTATED_SAVANNA_ROCK
      MUTATED_MESA: MUTATED_MESA
      MUTATED_MESA_ROCK: MUTATED_MESA_ROCK
      MUTATED_MESA_CLEAR_ROCK: MUTATED_MESA_CLEAR_ROCK
