Settings:
  AllowAutoCreate: true
  InteractWithSnitches: true
  MaxPowerTransfers: 8
  MaxBridgeLength: 16
  PlayerStateResetInSeconds: 300
  SwitchTimeout: 1000
  MaxRedstoneDistance: 7
  LogChanges: true
  Timer:
    Enabled: true
    Min: 1
    Max: 60
    DefaultInterval: 5
    DefaultOperation: UNDRAW
  GearblockMustBeReinforced: false
Blocks:
  GearMaterials:
  - STONE
  - GRASS
  - DIRT
  - COBBLESTONE
  - WOOD
  - LOG
  - GLASS
  - LAPIS_BLOCK
  - SANDSTONE
  - WOOL
  - GOLD_BLOCK
  - IRON_BLOCK
  - DOUBLE_STEP
  - STEP
  - BRICK
  - MOSSY_COBBLESTONE
  - OBSIDIAN
  - WOOD_STAIRS
  - DIAMOND_BLOCK
  - COBBLESTONE_STAIRS
  - ICE
  - SNOW_BLOCK
  - CLAY
  - FENCE
  - NETHERRACK
  - GLOWSTONE
  - SMOOTH_BRICK
  - IRON_FENCE
  - BRICK_STAIRS
  - SMOOTH_STAIRS
  - NETHER_BRICK
  - NETHER_FENCE
  - NETHER_BRICK_STAIRS
  - ENDER_STONE
  - WOOD_DOUBLE_STEP
  - WOOD_STEP
  - SANDSTONE_STAIRS
  - EMERALD_BLOCK
  - SPRUCE_WOOD_STAIRS
  - BIRCH_WOOD_STAIRS
  - JUNGLE_WOOD_STAIRS
  - COBBLE_WALL
  - REDSTONE_BLOCK
  - QUARTZ_BLOCK
  - QUARTZ_STAIRS
  - STAINED_CLAY
  - LOG_2
  - ACACIA_STAIRS
  - DARK_OAK_STAIRS
  - HAY_BLOCK
  - HARD_CLAY
  - COAL_BLOCK
  - PACKED_ICE
  - RED_SANDSTONE
  - RED_SANDSTONE_STAIRS
  - DOUBLE_STONE_SLAB2
  - STONE_SLAB2
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - DARK_OAK_FENCE
  - ACACIA_FENCE
  - PURPUR_BLOCK
  - PURPUR_STAIRS
  - PURPUR_DOUBLE_SLAB
  - PURPUR_SLAB
  - END_BRICKS
  - MAGMA
  - NETHER_WART_BLOCK
  - RED_NETHER_BRICK
  - BONE_BLOCK
  BridgeMaterials:
  - STONE
  - DIRT
  - COBBLESTONE
  - WOOD
  - LOG
  - GLASS
  - LAPIS_BLOCK
  - SANDSTONE
  - WOOL
  - GOLD_BLOCK
  - IRON_BLOCK
  - DOUBLE_STEP
  - STEP
  - BRICK
  - MOSSY_COBBLESTONE
  - WOOD_STAIRS
  - DIAMOND_BLOCK
  - COBBLESTONE_STAIRS
  - ICE
  - SNOW_BLOCK
  - CLAY
  - FENCE
  - NETHERRACK
  - GLOWSTONE
  - SMOOTH_BRICK
  - IRON_FENCE
  - BRICK_STAIRS
  - SMOOTH_STAIRS
  - NETHER_BRICK
  - NETHER_FENCE
  - NETHER_BRICK_STAIRS
  - ENDER_STONE
  - WOOD_DOUBLE_STEP
  - WOOD_STEP
  - SANDSTONE_STAIRS
  - EMERALD_BLOCK
  - SPRUCE_WOOD_STAIRS
  - BIRCH_WOOD_STAIRS
  - JUNGLE_WOOD_STAIRS
  - COBBLE_WALL
  - REDSTONE_BLOCK
  - QUARTZ_BLOCK
  - QUARTZ_STAIRS
  - STAINED_CLAY
  - LOG_2
  - ACACIA_STAIRS
  - DARK_OAK_STAIRS
  - HAY_BLOCK
  - HARD_CLAY
  - COAL_BLOCK
  - PACKED_ICE
  - RED_SANDSTONE
  - RED_SANDSTONE_STAIRS
  - DOUBLE_STONE_SLAB2
  - STONE_SLAB2
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - DARK_OAK_FENCE
  - ACACIA_FENCE
  - PURPUR_BLOCK
  - PURPUR_STAIRS
  - PURPUR_DOUBLE_SLAB
  - PURPUR_SLAB
  - END_BRICKS
Items:
  Tool:
    material: STICK
    lore: ''
  CreationConsume:
    material: IRON_BLOCK
    amount: 1
    lore: ''
